### PR TITLE
Added Impler to Projects

### PR DESCRIPTION
**Pull request by chavda-bhavik**

### CODE REVIEW

**Comment by elie222** [comment]
Thanks! Can you add the tech it uses too?

**Comment by chavda-bhavik** [comment]
Sure

**Comment by chavda-bhavik** [comment]
Done Elie. Just realized that the `Phoenix` list is no longer available and it is a [dead link](https://github.com/elie222/learn-from-open-source?tab=readme-ov-file#phoenix). Should I remove it?

**Comment by elie222** [comment]
> Done Elie. Just realized that the `Phoenix` list is no longer available and it is a [dead link](https://github.com/elie222/learn-from-open-source?tab=readme-ov-file#phoenix). Should I remove it?

Sure!

**Pull request merged**
