### PR TITLE
adding unkey

### PR DESCRIPTION
**Pull request by trace2798**

### CODE REVIEW

**Comment by elie222** [comment]
Thanks. Do you want to add Unkey to more sections like Tailwind and Next.js?

**Comment by trace2798** [comment]
Hey. Yes, that sounds good.

**Comment by elie222** [comment]
Should be added to contents too:
https://github.com/elie222/learn-from-open-source#table-of-contents

**Comment by trace2798** [comment]
@elie222 I am not sure about that. I think it will be a better fit to be added to just Projects for now.

**Comment by elie222** [comment]
Thanks for the PR!

**Pull request merged**
